name: Build and Release

permissions:
  contents: write

on:
    push:
        branches: ["master"]
    workflow_dispatch:

jobs:
  arduino_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$HOME/bin" >> $GITHUB_PATH
          echo "/home/runner/work/MEME_software/MEME_software/bin" >> $GITHUB_PATH
          export PATH=$PATH:/home/runner/work/MEME_software/MEME_software/bin

      - name: Configure Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Install Required Libraries
        run: |
          arduino-cli lib install "Servo"

      - name: Compile Arduino Code
        run: |
          make arduino

      - name: Upload Compiled Firmware as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: arduino_firmware
          path: build/sketch.ino.hex

  release:
    needs: arduino_build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_tag
        run: echo "TAG=v$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_ENV
      
      - name: Generate release notes
        run: |
          git log --pretty=format:"- %h %s (%an, %ad)" --date=short $(git describe --tags --abbrev=0 @^ 2>/dev/null || echo HEAD) > release_notes.md
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          body_path: release_notes.md
          draft: false
          prerelease: false

      - name: Download Arduino Build
        uses: actions/download-artifact@v4
        with:
          name: arduino_firmware
          path: build
      
      - name: Upload Arduino HEX
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/sketch.ino.hex
          asset_name: sketch.ino.hex
          asset_content_type: application/octet-stream
