name: Build and Release

permissions:
  contents: write

on:
    push:
        branches: ["master"]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create build folder
        run: |
          mkdir -p build
          ls build
      - name: Install dependencies
        run: make

  arduino_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$HOME/bin" >> $GITHUB_PATH
          echo "/home/runner/work/MEME/MEME/bin" >> $GITHUB_PATH
          export PATH=$PATH:/home/runner/work/MEME/MEME/bin

      - name: Configure Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Install Required Libraries
        run: |
          arduino-cli lib install "Servo"

      - name: Compile Arduino Code
        run: |
          arduino-cli compile -b arduino:avr:uno sketch --output-dir build --library ./include --build-property build.extra_flags="-DTESTING=false -DSCANS_PER_SWIPE=10" 
          
      - name: Rename Hex
        run: |
          mv build/sketch.ino.hex build/main_arduino.hex

      - name: Upload Compiled Firmware
        uses: actions/upload-artifact@v4
        with:
          name: main_arduino
          path: build/main_arduino.hex

  
  testing_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build EXE (TESTING)
        run: |
          make TESTING=true
          ls build
      
      - name: Upload Compiled Binary
        uses: actions/upload-artifact@v4
        with:
          name: main_testing
          path: build/main_testing.exe

  release:
    needs: [build, arduino_build, testing_build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_tag
        run: echo "tag=v$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_ENV
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: Release ${{ env.tag }}
          draft: false
          prerelease: false

      - name: Download Compiled Binary
        uses: actions/download-artifact@v4
        with:
          name: main_testing
          path: build

      - name: Download Arduino Build
        uses: actions/download-artifact@v4
        with:
          name: main_arduino
          path: build

      - name: Upload EXE
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/main_testing.exe
          asset_name: main_testing.exe
          asset_content_type: application/octet-stream
      
      - name: Upload Arduino HEX
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/main_arduino.hex
          asset_name: main_arduino.hex
          asset_content_type: application/octet-stream